apiVersion: 1
contactPoints:
    - orgId: 1
      name: Alert Webhook
      receivers:
        - uid: dfao7fp74dlvke
          type: webhook
          settings:
            httpMethod: POST
            password: admin
            url: http://host.docker.internal:5000/webhook/alert
          disableResolveMessage: false